/* This file contains the definitions for the various dialog boxes defined in
chart.rc. */

#define iddNull         -1

#define iddSeqSeries    1
#define iddSeqCategory  2
#define iddSeqValue     3
#define iddSeqFirst     4
#define iddSeqIncrement 5
#define iddSeqOk        6
#define iddSeqCancel    7

#define iddDatSeries    1
#define iddDatCategory  2
#define iddDatValue     3
#define iddDatFirst     4
#define iddDatIncrement 5
#define iddDatYears     6
#define iddDatMonths    7
#define iddDatDays      8
#define iddDatWeekdays  9
#define iddDatOk        10
#define iddDatCancel    11

#define iddTxtSeries    1
#define iddTxtCategory  2
#define iddTxtValue     3
#define iddTxtOk        4
#define iddTxtCancel    5

#define iddNumSeries    1
#define iddNumCategory  2
#define iddNumValue     3
#define iddNumOk        4
#define iddNumCancel    5

#define iddSrtCategory  1
#define iddSrtValue     2
#define iddSrtAscend    3
#define iddSrtDescend   4
#define iddSrtOk        5
#define iddSrtCancel    6

#define iddAnaAverage   1
#define iddAnaTrend     2
#define iddAnaGrowth    3
#define iddAnaSum       4
#define iddAnaDiff      5
#define iddAnaPercent   6
#define iddAnaStats     7
#define iddAnaOk        8
#define iddAnaCancel    9
