
/* Menu MenuBar */
/* Popup menu Gallery */
#define GALLERY 0
#define IDPGALLERY 256
#define COLUMN 0
#define IDMCOLUMN 256
#define BAR 1
#define IDMBAR 257
/* Popup menu Data */
#define DATA 1
#define IDPDATA 258
#define INCREMENT 0
#define IDMINCREMENT 258
#define DECREMENT 1
#define IDMDECREMENT 259
/* Popup menu Size */
#define SIZE 2
#define IDPSIZE 260
#define CLIP 0
#define IDMCLIP 260
#define SCALE 1
#define IDMSCALE 261
#define SETSIZE 3
#define IDMSETSIZE 263
/* Popup menu Debug */
#define DEBUG 3
#define IDPDEBUG 264
#define DEBUGMI1 0
#define IDMDEBUGMI1 264
#define DEBUGMI2 1
#define IDMDEBUGMI2 265
#define DEBUGMI3 2
#define IDMDEBUGMI3 266
#define DEBUGMI4 3
#define IDMDEBUGMI4 267
#define DEBUGMI5 4
#define IDMDEBUGMI5 268
#define DEBUGDLG 5
#define IDMDEBUGDLG 269

/* Menu OkCancel */
#define IDMOK 256
#define IDMCANCEL 257

/* Dialog IDIFIGSIZE */
#define IDDCMNTWIDTH 1
#define IDDCMNTHT 2
#define IDDCMNTXORG 3
#define IDDCMNTYORT 4
#define IDDCMNTCITEMS 5
#define IDDWIDTH 6
#define IDDHEIGHT 7
#define IDDXORIGIN 8
#define IDDYORIGIN 9
#define IDDCITEMS 10

/* Dialog IDIDEBUG */
#define IDDDBGLTXT1 11
#define IDDDBGLTXT2 12
#define IDDDBGLTXT3 13
#define IDDDBGLTXT4 14
#define IDDDBGLTXT5 15
#define IDDDBGTXT1 16
#define IDDDBGTXT2 17
#define IDDDBGTXT3 18
#define IDDDBGTXT4 19
#define IDDDBGTXT5 20
#define IDDDBGPB1 21
#define IDDDBGPB2 22
#define IDDDBGPB3 23
#define IDDDBGPB4 24
#define IDDDBGPB5 25
#define IDDDBGRB1 26
#define IDDDBGRB2 27
#define IDDDBGRB3 28
#define IDDDBGRB4 29
#define IDDDBGRB5 30
#define IDDDBGCB1 31
#define IDDDBGCB2 32
#define IDDDBGCB3 33
#define IDDDBGCB4 34
#define IDDDBGCB5 35

/* Dialog IDIQUIT */
#define IDDQUITTXT 36
#define IDDYES 37
#define IDDNO 38
